name: "deployment-1"
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the workflow has write permissions
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test Code
        run: npm run test

      - name: Build Code
        run: npm run build

      - name: Deploy Code
        run: echo "Deploying Code"

      - name: Commit Changes with Repository Name
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update from ${{ github.repository }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
