name: "deployment-2"
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci 
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test Code
        run: npm run test 

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]  # Ensures lint and test jobs complete before deploy
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build Code 
        run: npm run build  # Fixed case sensitivity
      - name: Deploy Code
        run: echo "Deploying Code"
